---
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: ''
  #  existingVolume: "my-existing-volume"
ingress:
  enabled: false  # Traditional ingress
service:
  # Service type (ClusterIP, NodePort, LoadBalancer, or ExternalName)
  type: ClusterIP
# serviceMonitor:
#  enabled: true
#  scrapeInterval: 30s
#  labels:
#    release: prometheus
#  # Bearer token authentication configuration (optional)
#  bearerToken:
#    secretName: "prometheus-token"
#    secretKey: "token"
# additionalVolumes:
#  - hostPath:
#      path: >-
#        /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230509111242-if00
#      type: CharDevice
#    name: usb
#
# additionalMounts:
#  - mountPath: /dev/ttyACM0
#    name: usb
# initContainers:
#  - name: init-myservice
#    image: busybox
#    command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
## Configuration for Home Assistant
# configuration:
#  # Enable or disable the configuration setup for Home Assistant
#  enabled: true
#  # Force init will merge the current configuration file with the default configuration on every start
#  # This is useful when you want to ensure that the configuration file is always up to date
#  forceInit: true
#  # List of trusted proxies in the format of CIDR notation in a case of using a reverse proxy
#  # Here is the list of the most common private IP ranges, use your list of possible trusted proxies, usually, it's the IP of the reverse proxy
#  trusted_proxies:
#    - 10.42.0.0/16  # Add the IP address of your cluster CIDR
#  # Editing templateConfig allows you to customize the configuration.yaml file
#  # You can use Go template functions to customize the configuration
#  templateConfig: |-
#    # Loads default set of integrations. Do not remove.
#    default_config:
#
#    {{- if .Values.ingress.enabled }}
#    http:
#      use_x_forwarded_for: true
#      trusted_proxies:
#        {{- range .Values.configuration.trusted_proxies }}
#        - {{ . }}
#        {{- end }}
#    {{- end}}
#    # Load frontend themes from the themes folder
#    frontend:
#      themes: !include_dir_merge_named themes
#
#    automation: !include automations.yaml
#    script: !include scripts.yaml
#    scene: !include scenes.yaml
